### ISSUE TITLE
Análisis del frontend base

### ISSUE THREAD

**Issue by arturorc** [dgb-sistemas/biblat-manager#1]
## Criterios de aceptación

* Estructura base

## Duración

* 1 día, 3 horas

**Comment by EJAJDGB** [comment]
Estoy haciendo el analisis de los archivos html, que se ecuentran en el drive. Tengo duda si es solo de estos o existen mas.

**Comment by arturorc** [comment]
@EJAJDGB sí, solo es lo que se tiene en Proyectos -> Biblat-manager -> HTML
![screen shot 2018-05-18 at 12 31 34 pm](https://user-images.githubusercontent.com/19309726/40249073-87c30cc2-5a97-11e8-9d59-8fb708b448f8.png)

**Comment by EJAJDGB** [comment]
<!doctype html>


<html lang="en">

# 
<head>
	<meta charset="UTF-8">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="efrain" >
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title></title>
	<link rel="icon" href="/img/favicon.png" sizes="any" type="image/x-icon">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
	 crossorigin="anonymous">
	<link rel="stylesheet" href="css/style.min.css">
	<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
	 crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	 crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js" integrity="sha256-19J3rT3tQdidgtqqdQ3xNu++Gd7EoP/ag/0x1lHi0xY="
	 crossorigin="anonymous"></script>
	<script src="js/bootstrap-material-design.min.js"></script>
	<script src="js/biblat.min.js"></script>
</head>
# 

<body>
	<div class="login-page">
		<div class="page-header">
			<div class="container h-100">
				<div class="row align-items-center h-100">
					<div class="col-sm-6 col-12 mx-auto">
						<div class="card">
							<div class="card-header card-header-primary text-center">
								<h2>Iniciar sesión</h2>
								<h4>Ir a
									<span class="font-weight-bold">Biblat Manager</span>
								</h4>
							</div>


# 
							<form class="card-body" action="/login" method="post">
								<div class="form-group">
									<label>Correo electrónico</label>
									<div class="input-group">
										<div class="input-group-prepend">
											<span class="input-group-text">
												<i class="material-icons">email</i>
											</span>
										</div>
										<input type="email" class="form-control" name="email" placeholder="(e.g. juan.hernandez@unam.mx)" required>
									</div>
								</div>
								<div class="form-group">
									<label>Contraseña</label>
									<div class="input-group">
										<div class="input-group-prepend">
											<span class="input-group-text">
												<i class="material-icons">vpn_key</i>
											</span>
										</div>
										<input type="password" class="form-control" name="password" placeholder="••••••••" required>
									</div>
								</div>
								<div class="form-group">
									<a href="#" class="" target="_blank">¿Olvidó su contraseña?</a>
								</div>
								<div class="form-group">
									<button type="submit" class="btn btn-primary btn-lg btn-block">Acceder</button>
								</div>
							</form>
						</div>
# 
						
						
# 
						<footer class="footer">
							<div class="container">
								<p>
									&copy;
									<script>
										document.write(new Date().getFullYear())
									</script> Todos los derechos reservados. Dirección General de Bibliotecas, UNAM.
								</p>
							</div>
						</footer>
# 

					</div>
				</div>
			</div>
		</div>
	</div>
</body>

</html>

**Comment by EJAJDGB** [comment]
<!doctype html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="efrain" >
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title></title>
	<link rel="icon" href="/img/favicon.png" sizes="any" type="image/x-icon">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
	 crossorigin="anonymous">
	 
#	 ************ Quitar diagonal de mas "/" ************
	<link rel="stylesheet" href="css/style.min.css">
	<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
	 crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	 crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js" integrity="sha256-19J3rT3tQdidgtqqdQ3xNu++Gd7EoP/ag/0x1lHi0xY="
	 crossorigin="anonymous"></script>
	 
	 
	<script src="js/bootstrap-material-design.min.js"></script>
	
	
	<script src="js/biblat.min.js"></script>
</head>

<body>
	<div class="wrapper">

# ************ Archivo sidebar (sidebar.html) ************
		<div class="sidebar" data-color="purple" data-background-color="white" data-image="../img/sidebar.jpg">
			<div class="logo">
				<a href="#" class="simple-text logo-normal">
					Biblat Manager
				</a>
			</div>
			<div class="sidebar-wrapper">
				<ul class="nav">
					<li class="nav-item active">
						<a class="nav-link" href="#">
							<i class="fas fa-bookmark"></i>
							<p>Revistas</p>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">
							<i class="fas fa-university"></i>
							<p>Institución</p>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">
							<i class="fas fa-balance-scale"></i>
							<p>Licencias</p>
						</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="main-panel">
# ************ (sidebar.html) ************
		
# ************ Archivo navegacion (navbar.html)) ************
			<nav class="navbar navbar-expand-lg navbar-transparent  navbar-absolute fixed-top">
				<div class="container-fluid">
					<div class="navbar-wrapper">
						<a class="navbar-brand" href="#pablo">Revista mexicana de física</a>
					</div>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index"
					 aria-expanded="false" aria-label="Toggle navigation">
						<span class="sr-only">Toggle navigation</span>
						<span class="navbar-toggler-icon icon-bar"></span>
						<span class="navbar-toggler-icon icon-bar"></span>
						<span class="navbar-toggler-icon icon-bar"></span>
					</button>
					<div class="collapse navbar-collapse justify-content-end" id="navigation">
						<form class="navbar-form">
							<div class="input-group no-border">
								<input type="text" value="" class="form-control" placeholder="Buscar">
								<button type="submit" class="btn btn-white btn-round btn-just-icon">
									<i class="material-icons">search</i>
									<div class="ripple-container"></div>
								</button>
							</div>
						</form>
						<ul class="navbar-nav">
							<li class="nav-item">
								<a class="nav-link" href="#">
									<i class="fas fa-user-circle fa-lg"></i>
									<p>
										<span class="d-lg-none d-md-block">Perfil</span>
									</p>
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">
									<i class="fas fa-sign-out-alt fa-lg"></i>
									<p>
										<span class="d-lg-none d-md-block">Cerrar sesión</span>
									</p>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</nav>
#  ************ (navbar.html)) ************
# ************ Archivo de Contenido **************
			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="col-md-12">
							<div class="card">
								<div class="card-header card-header-tabs card-header-primary">
									<div class="nav-tabs-navigation">
										<div class="nav-tabs-wrapper">
											<ul class="nav nav-tabs" data-tabs="tabs">
												<li class="nav-item">
													<a class="nav-link" href="#navLink1" data-toggle="tab">
														Acerca
														<div class="ripple-container"></div>
													</a>
												</li>
												<li class="nav-item">
													<a class="nav-link active" href="#navLink2" data-toggle="tab">
														Fascículos
														<div class="ripple-container"></div>
													</a>
												</li>
												<li class="nav-item">
													<a class="nav-link" href="#navLink3" data-toggle="tab">
														Notificaciones
														<span class="badge badge-default">24</span>
														<div class="ripple-container"></div>
													</a>
												</li>
											</ul>
										</div>
									</div>
								</div>
								<div class="card-body">
									<div class="tab-content">
										<div class="tab-pane" id="navLink1">
											<div class="table-responsive">
												<table class="table table-shopping">
													<tbody>
														<tr>
															<td>
																<div class="img-container">
																	<img src="https://78.media.tumblr.com/38755be8061a87520db8f5a06cd385f4/tumblr_oedf7yDxx01tx3yxdo1_500.gif" alt="...">
																</div>
															</td>
															<td class="td-name">
																<a href="#">Revista mexicana de física</a>
																<br>
																<small>
																	<strong>Título corto: </strong>Rev. mex. fis.</small>
																<br>
																<small>
																	<strong>ISSN: </strong>0035-001X</small>
																<br>
																<small>
																	<strong>e-ISSN: </strong>
																</small>
																<br>
																<small>
																	<strong>Licencia CC: </strong>BY-NC/4.0</small>
															</td>
														</tr>
													</tbody>
												</table>
											</div>
										</div>
										<div class="tab-pane active" id="navLink2">
											<form>
												<div class="form-group">
													<label class="bmd-label-floating">
														Año
														<span class="text-danger">*</span>
													</label>
													<input type="text" class="form-control" required>
												</div>
												<div class="form-group">
													<label class="bmd-label-floating">
														Volumen
													</label>
													<input type="text" class="form-control" required>
												</div>
												<div class="form-group">
													<label class="bmd-label-floating">
														Número
													</label>
													<input type="text" class="form-control" required>
												</div>
												<div class="form-group">
													<label>Mes inicial</label>
													<select class="selectpicker " data-style="select-with-transition" title="Seleccionar mes" data-size="7">
														<option value="1">Enero</option>
													</select>
												</div>
												<div class="form-group">
													<label>Mes inicial</label>
													<select class="selectpicker " data-style="select-with-transition" title="Seleccionar mes" data-size="7">
														<option value="1">Febrero</option>
													</select>
												</div>
												<div class="form-group">
													<button type="submit" class="btn btn-primary btn-lg btn-block">Guardar</button>
												</div>
											</form>
										</div>
										<div class="tab-pane" id="navLink3"></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
# ***************** Contenido
			

			<footer class="footer">
				<div class="container-fluid">
					<div class="copyright float-right">
						&copy;
						<script>
							document.write(new Date().getFullYear())
						</script> Todos los derechos reservados. Dirección General de Bibliotecas, UNAM.
					</div>
				</div>
			</footer>

		</div>
	</div>
</body>

</html>

**Comment by iduranm** [comment]
## Sobre tú comentario anterior

___

> No entiendo a qué te refieres con lo siguiente:
** Quitar diagonal de mas "/" **

Gracias!

**Comment by iduranm** [comment]
## Pregunta sobre el esquema base

Cómo quedará el esquema base ya codificado? Todo en un sólo archivo o varios archivos dependiendo del análisis que ya realizaste?

Por ejemplo, un archivo para header, otro para footer y así sucesivamente

**Comment by iduranm** [comment]
```mermaid
sequenceDiagram
Alice ->> Bob: Hello Bob, how are you?

**Comment by iduranm** [comment]
```mermaid
sequenceDiagram
Alice ->> Bob: Hello Bob, how are you?

**Comment by EJAJDGB** [comment]
En el comentario de "Quitar diagonal de mas". Existen en las importaciones de algunos archivos diagonales de más que impiden que se cargen. O sea, generan excepciones del tipo "Archivo no encontrado". Como es el caso de:

<script src="/js/bootstrap-material-design.min.js"></script>

La diagonal que comienza la ruta relativa del archivo "/js/bootstrap-material-design.min.js" esta de más. Lo correcto es "js/bootstrap-material-design.min.js"

**Comment by iduranm** [comment]
Ok perfect. Pues si ya se las quitaste deja las pruebo.

**Comment by iduranm** [comment]
## Análisis del FrontEnd Base

Sólo se requieren 3 archivos:
- header.html
- sidebar.html
- footer.html

**Comment by iduranm** [comment]
## header.html

<!doctype html>

<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="efrain" >
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title></title>
	<link rel="icon" href="/img/favicon.png" sizes="any" type="image/x-icon">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
	 crossorigin="anonymous">
	<link rel="stylesheet" href="css/style.min.css">
	<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
	 crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	 crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js" integrity="sha256-19J3rT3tQdidgtqqdQ3xNu++Gd7EoP/ag/0x1lHi0xY="
	 crossorigin="anonymous"></script>
	<script src="js/bootstrap-material-design.min.js"></script>
	<script src="js/biblat.min.js"></script>
</head>
<body>

<div class="wrapper">
  <div class="login-page">
    <div class="page-header">



    </div>
  </div>
</div>

</body>

</html>

**Comment by iduranm** [comment]
## sidebar.html

<div class="sidebar" data-color="purple" data-background-color="white" data-image="../img/sidebar.jpg">
  <div class="logo">
    <a href="#" class="simple-text logo-normal">
      Biblat Manager
    </a>
  </div>
  <div class="sidebar-wrapper">
    <ul class="nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">
          <i class="fas fa-bookmark"></i>
          <p>Revistas</p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="fas fa-university"></i>
          <p>Institución</p>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="fas fa-balance-scale"></i>
          <p>Licencias</p>
        </a>
      </li>
    </ul>
  </div>
</div>

**Comment by iduranm** [comment]
## footer.html

<footer class="footer">
  <div class="container-fluid">
    <div class="copyright float-right">
      &copy;
      <script>
        document.write(new Date().getFullYear())
      </script> Todos los derechos reservados. Dirección General de Bibliotecas, UNAM.
    </div>
  </div>
</footer>

**Comment by EJAJDGB** [comment]
Que tal. Segun recuerdo en Flask se pueden usar plantillas o templates.

Tomando en cuenta esto, solo quedaria un archivo base llamado base_layout.html. Lo pongo aqui. Los espacio que habria que llenar estan marcados por las etiquetas de Jinja

<!doctype html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="efrain" >
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title></title>
	<link rel="icon" href="img/favicon.png" sizes="any" type="image/x-icon">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
	 crossorigin="anonymous">
	<link rel="stylesheet" href="css/style.min.css">
	<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
	 crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	 crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js" integrity="sha256-19J3rT3tQdidgtqqdQ3xNu++Gd7EoP/ag/0x1lHi0xY="
	 crossorigin="anonymous"></script>
	<script src="js/bootstrap-material-design.min.js"></script>
	<script src="js/biblat.min.js"></script>
</head>

<body>
	<div class="wrapper">
		<div class="sidebar" data-color="purple" data-background-color="white" data-image="../img/sidebar.jpg">
			<div class="logo">
				<a href="#" class="simple-text logo-normal">
					Biblat Manager
				</a>
			</div>
			<div class="sidebar-wrapper">
				<ul class="nav">
					<li class="nav-item active">
						<a class="nav-link" href="#">
							<i class="fas fa-bookmark"></i>
							<p>Revistas</p>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">
							<i class="fas fa-university"></i>
							<p>Institución</p>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">
							<i class="fas fa-balance-scale"></i>
							<p>Licencias</p>
						</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="main-panel">
			<nav class="navbar navbar-expand-lg navbar-transparent  navbar-absolute fixed-top">
				<div class="container-fluid">
					<div class="navbar-wrapper">
						
						{% block titulo_pagina %}{% endblock %}
					</div>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index"
					 aria-expanded="false" aria-label="Toggle navigation">
						<span class="sr-only">Toggle navigation</span>
						<span class="navbar-toggler-icon icon-bar"></span>
						<span class="navbar-toggler-icon icon-bar"></span>
						<span class="navbar-toggler-icon icon-bar"></span>
					</button>
					<div class="collapse navbar-collapse justify-content-end" id="navigation">
						<form class="navbar-form">
							<div class="input-group no-border">
								<input type="text" value="" class="form-control" placeholder="Buscar">
								<button type="submit" class="btn btn-white btn-round btn-just-icon">
									<i class="material-icons">search</i>
									<div class="ripple-container"></div>
								</button>
							</div>
						</form>
						<ul class="navbar-nav">
							<li class="nav-item">
								<a class="nav-link" href="#">
									<i class="fas fa-user-circle fa-lg"></i>
									<p>
										<span class="d-lg-none d-md-block">Perfil</span>
									</p>
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">
									<i class="fas fa-sign-out-alt fa-lg"></i>
									<p>
										<span class="d-lg-none d-md-block">Cerrar sesión</span>
									</p>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</nav>
			<div class="content">
			
				
				{% block contenido %}{% endblock %}
				
			</div>
			<footer class="footer">
				<div class="container-fluid">
					<div class="copyright float-right">
						&copy;
						<script>
							document.write(new Date().getFullYear())
						</script> Todos los derechos reservados. Dirección General de Bibliotecas, UNAM.
					</div>
				</div>
			</footer>
		</div>
	</div>
</body>

</html>
