### ISSUE TITLE
Desarrollo de template base

### ISSUE THREAD

**Issue by arturorc** [dgb-sistemas/biblat-manager#2]
## Criterios de aceptación

* Template base de acuerdo al mockup inicial

## Duración

* 1 día, 3 horas.

**Comment by EJAJDGB** [comment]
Aqui les pongo el template. El archivo es base_layout.html.

<!doctype html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="efrain" >
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title></title>
	<link rel="icon" href="img/favicon.png" sizes="any" type="image/x-icon">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
	 crossorigin="anonymous">
	<link rel="stylesheet" href="css/style.min.css">
	<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
	 crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	 crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js" integrity="sha256-19J3rT3tQdidgtqqdQ3xNu++Gd7EoP/ag/0x1lHi0xY="
	 crossorigin="anonymous"></script>
	<script src="js/bootstrap-material-design.min.js"></script>
	<script src="js/biblat.min.js"></script>
</head>

<body>
	<div class="wrapper">
		<div class="sidebar" data-color="purple" data-background-color="white" data-image="../img/sidebar.jpg">
			<div class="logo">
				<a href="#" class="simple-text logo-normal">
					Biblat Manager
				</a>
			</div>
			<div class="sidebar-wrapper">
				<ul class="nav">
					<li class="nav-item active">
						<a class="nav-link" href="#">
							<i class="fas fa-bookmark"></i>
							<p>Revistas</p>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">
							<i class="fas fa-university"></i>
							<p>Institución</p>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">
							<i class="fas fa-balance-scale"></i>
							<p>Licencias</p>
						</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="main-panel">
			<nav class="navbar navbar-expand-lg navbar-transparent  navbar-absolute fixed-top">
				<div class="container-fluid">
					<div class="navbar-wrapper">
						
						{% block titulo_pagina %}{% endblock %}
					</div>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index"
					 aria-expanded="false" aria-label="Toggle navigation">
						<span class="sr-only">Toggle navigation</span>
						<span class="navbar-toggler-icon icon-bar"></span>
						<span class="navbar-toggler-icon icon-bar"></span>
						<span class="navbar-toggler-icon icon-bar"></span>
					</button>
					<div class="collapse navbar-collapse justify-content-end" id="navigation">
						<form class="navbar-form">
							<div class="input-group no-border">
								<input type="text" value="" class="form-control" placeholder="Buscar">
								<button type="submit" class="btn btn-white btn-round btn-just-icon">
									<i class="material-icons">search</i>
									<div class="ripple-container"></div>
								</button>
							</div>
						</form>
						<ul class="navbar-nav">
							<li class="nav-item">
								<a class="nav-link" href="#">
									<i class="fas fa-user-circle fa-lg"></i>
									<p>
										<span class="d-lg-none d-md-block">Perfil</span>
									</p>
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#">
									<i class="fas fa-sign-out-alt fa-lg"></i>
									<p>
										<span class="d-lg-none d-md-block">Cerrar sesión</span>
									</p>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</nav>
			<div class="content">
			
				
				{% block contenido %}{% endblock %}
				
			</div>
			<footer class="footer">
				<div class="container-fluid">
					<div class="copyright float-right">
						&copy;
						<script>
							document.write(new Date().getFullYear())
						</script> Todos los derechos reservados. Dirección General de Bibliotecas, UNAM.
					</div>
				</div>
			</footer>
		</div>
	</div>
</body>

</html>

**Comment by arturorc** [comment]
@EJAJDGB si es aún no esta completo esta bien aquí pero con el código comentado de forma adecuada:

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code
http://www.rubycoloredglasses.com/2013/04/languages-supported-by-github-flavored-markdown/
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

Si la plantilla ya esta completa entonces por favor hay realizar la integración al proyecto en flask y enviar el PR correspondiente, para esto necesito saber sus evaluaciones del PR #8 @iduranm @EJAJDGB
